-- https://adventofcode.com/2022/day/4

CREATE TABLE DAY4 (A TEXT, B TEXT);
.mode csv
.separator ","
.import 04/input.csv DAY4
ALTER TABLE DAY4 ADD COLUMN AMIN INT;
ALTER TABLE DAY4 ADD COLUMN AMAX INT;
ALTER TABLE DAY4 ADD COLUMN BMIN INT;
ALTER TABLE DAY4 ADD COLUMN BMAX INT;
UPDATE DAY4 SET AMIN = CAST(SUBSTR(A, 0, instr(A, '-')) AS INT);
UPDATE DAY4 SET AMAX = CAST(SUBSTR(A, INSTR(A, '-') + 1) AS INT);
UPDATE DAY4 SET BMIN = CAST(SUBSTR(B, 0, INSTR(B, '-')) AS INT);
UPDATE DAY4 SET BMAX = CAST(SUBSTR(B, INSTR(B, '-') + 1) AS INT);
ALTER TABLE DAY4 ADD COLUMN fully_contains INT;
UPDATE DAY4 SET fully_contains =
   (CASE WHEN (AMIN BETWEEN BMIN AND BMAX) AND (AMAX BETWEEN BMIN AND BMAX) THEN 1
   WHEN (BMIN BETWEEN AMIN AND AMAX) AND (BMAX BETWEEN AMIN AND AMAX) THEN 1
   ELSE 0 END);
SELECT SUM(fully_contains) FROM DAY4;
-- PART 2
ALTER TABLE DAY4 ADD COLUMN overlap INT;
UPDATE DAY4 SET overlap =
   (CASE WHEN (AMIN BETWEEN BMIN AND BMAX) OR (AMAX BETWEEN BMIN AND BMAX) THEN 1
   WHEN (BMIN BETWEEN AMIN AND AMAX) OR (BMAX BETWEEN AMIN AND AMAX) THEN 1
   ELSE 0 END);
SELECT SUM(overlap) FROM DAY4;